#配置eureka服务注册中心
server:
  port: 10086  #配置注册中心的端口

# 配置服务的名称
spring:
  application:
    name: ly-registry

# 配置eureka服务中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    fetch-registry: false  #从Eureka Server服务的列表只读备份，然后缓存在本地
    register-with-eureka: false # 不把自己注册到eureka注册中心中


